// examples/chat/native/angular/src/approval.component.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';
import type { ApplicationSnapshot } from '../../shared/application';
import type { Application } from './application.token';

@Component({
  selector: 'native-approval',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (snapshot().selection.status === 'ready') { @if (snapshot().decision; as
    decision) {
    <section class="approval" aria-labelledby="approval-title">
      <h2 id="approval-title">Approval request</h2>
      <p class="approval-reason">{{ decision.reason }}</p>
      <div class="approval-actions">
        <button
          type="button"
          [disabled]="!decision.canRespond"
          (click)="application().respond(decision.token, 'approve')"
        >
          Approve request
        </button>
        <button
          type="button"
          [disabled]="!decision.canRespond"
          (click)="application().respond(decision.token, 'decline')"
        >
          Decline request
        </button>
      </div>
    </section>
    } @else if (snapshot().runtime?.interrupts?.length) {
    <p role="status">
      This conversation is waiting for a response this example does not support.
    </p>
    } }
  `,
})
export class ApprovalComponent {
  readonly application = input.required<Application>();
  readonly snapshot = input.required<ApplicationSnapshot>();
}

// examples/chat/native/react/src/approval.tsx
import type {
  ApplicationSnapshot,
  createApplication,
} from '../../shared/application';

export function Approval({
  application,
  snapshot,
}: {
  application: ReturnType<typeof createApplication>;
  snapshot: ApplicationSnapshot;
}) {
  if (snapshot.selection.status !== 'ready') return null;
  const decision = snapshot.decision;
  if (!decision)
    return snapshot.runtime?.interrupts.length ? (
      <p role="status">
        This conversation is waiting for a response this example does not
        support.
      </p>
    ) : null;
  const { token, reason, canRespond } = decision;
  return (
    <section className="approval" aria-labelledby="approval-title">
      <h2 id="approval-title">Approval request</h2>
      <p className="approval-reason">{reason}</p>
      <div className="approval-actions">
        <button
          type="button"
          disabled={!canRespond}
          onClick={() => application.respond(token, 'approve')}
        >
          Approve request
        </button>
        <button
          type="button"
          disabled={!canRespond}
          onClick={() => application.respond(token, 'decline')}
        >
          Decline request
        </button>
      </div>
    </section>
  );
}
