// libs/angular/chat/src/tool-observation.component.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';

/** Literal observed text. The caller owns tool/result association and formatting. */
@Component({
  selector: 'threadplane-tool-observation',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section [attr.aria-label]="label()">
      <h3>{{ name() }}</h3>
      <dl>
        <dt>Arguments</dt>
        <dd>
          <pre>{{ argumentsText() }}</pre>
        </dd>
        @if (resultText() !== undefined) {
        <dt>Result</dt>
        <dd>
          <pre>{{ resultText() }}</pre>
        </dd>
        }
      </dl>
    </section>
  `,
  styles: `
    :host { display: block; color: var(--ds-text-primary, #142435); font-family: inherit; overflow-wrap: anywhere; }
    dl, dd { margin: 0; }
    dt { font-weight: 600; }
    pre { margin-block: .25rem; white-space: pre-wrap; overflow-wrap: anywhere; }
  `,
})
export class ToolObservationComponent {
  readonly name = input.required<string>();
  readonly argumentsText = input.required<string>();
  readonly resultText = input<string>();
  readonly label = input('Tool observation');
}

// libs/react/src/chat/tool-observation.tsx
/** Literal observed text. The caller owns tool/result association and formatting. */
export interface ToolObservationProps {
  readonly name: string;
  readonly argumentsText: string;
  readonly resultText?: string;
  readonly label?: string;
}
/** Display supplied tool text without interpreting execution status. */
export function ToolObservation({
  name,
  argumentsText,
  resultText,
  label = 'Tool observation',
}: ToolObservationProps) {
  return (
    <section
      aria-label={label}
      style={{
        color: 'var(--ds-text-primary, #142435)',
        fontFamily: 'inherit',
        overflowWrap: 'anywhere',
      }}
    >
      <h3>{name}</h3>
      <dl style={{ margin: 0 }}>
        <dt style={{ fontWeight: 600 }}>Arguments</dt>
        <dd style={{ margin: 0 }}>
          <pre
            style={{
              whiteSpace: 'pre-wrap',
              overflowWrap: 'anywhere',
              marginBlock: '.25rem',
            }}
          >
            {argumentsText}
          </pre>
        </dd>
        {resultText !== undefined && (
          <>
            <dt style={{ fontWeight: 600 }}>Result</dt>
            <dd style={{ margin: 0 }}>
              <pre
                style={{
                  whiteSpace: 'pre-wrap',
                  overflowWrap: 'anywhere',
                  marginBlock: '.25rem',
                }}
              >
                {resultText}
              </pre>
            </dd>
          </>
        )}
      </dl>
    </section>
  );
}
