// libs/angular/markdown/src/markdown.component.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';
import {
  markdownUrl,
  type MarkdownNode,
  type MarkdownSnapshot,
} from '@threadplane/content/markdown';
import { MarkdownImageComponent } from './markdown-image.component';
import {
  MarkdownNodesDirective,
  MarkdownOutletDirective,
} from './markdown-template.directive';

@Component({
  selector: 'threadplane-markdown',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    MarkdownNodesDirective,
    MarkdownOutletDirective,
    MarkdownImageComponent,
  ],
  template: `
    @for (document of [snapshot().document]; track document.generation) {
    @if (snapshot().root; as root) {
    <ng-container
      [markdownOutlet]="nodesView"
      [markdownContext]="{
        $implicit: root.children,
        root,
        anchor: false,
        header: false
      }"
    />
    } }
    <ng-template
      #nodesView
      markdownNodes
      let-nodes
      let-root="root"
      let-anchor="anchor"
      let-header="header"
    >
      @for (node of nodes; track node.type + ':' + node.id) { @switch
      (node.type) { @case ('document') {
      <ng-container
        [markdownOutlet]="nodesView"
        [markdownContext]="{
          $implicit: node.children,
          root: node,
          anchor,
          header
        }"
      />
      } @case ('paragraph') {
      <p>
        <ng-container
          [markdownOutlet]="nodesView"
          [markdownContext]="{ $implicit: node.children, root, anchor, header }"
        />
      </p>
      } @case ('heading') { @switch (node.level) { @case (1) {
      <h1>
        <ng-container
          [markdownOutlet]="nodesView"
          [markdownContext]="{ $implicit: node.children, root, anchor, header }"
        />
      </h1>
      } @case (2) {
      <h2>
        <ng-container
          [markdownOutlet]="nodesView"
          [markdownContext]="{ $implicit: node.children, root, anchor, header }"
        />
      </h2>
      } @case (3) {
      <h3>
        <ng-container
          [markdownOutlet]="nodesView"
          [markdownContext]="{ $implicit: node.children, root, anchor, header }"
        />
      </h3>
      } @case (4) {
      <h4>
        <ng-container
          [markdownOutlet]="nodesView"
          [markdownContext]="{ $implicit: node.children, root, anchor, header }"
        />
      </h4>
      } @case (5) {
      <h5>
        <ng-container
          [markdownOutlet]="nodesView"
          [markdownContext]="{ $implicit: node.children, root, anchor, header }"
        />
      </h5>
      } @case (6) {
      <h6>
        <ng-container
          [markdownOutlet]="nodesView"
          [markdownContext]="{ $implicit: node.children, root, anchor, header }"
        />
      </h6>
      } } } @case ('blockquote') {
      <blockquote>
        <ng-container
          [markdownOutlet]="nodesView"
          [markdownContext]="{ $implicit: node.children, root, anchor, header }"
        />
      </blockquote>
      } @case ('list') { @if (node.ordered) {
      <ol [attr.start]="node.start">
        <ng-container
          [markdownOutlet]="nodesView"
          [markdownContext]="{ $implicit: node.children, root, anchor, header }"
        />
      </ol>
      } @else {
      <ul>
        <ng-container
          [markdownOutlet]="nodesView"
          [markdownContext]="{ $implicit: node.children, root, anchor, header }"
        />
      </ul>
      } } @case ('list-item') {
      <li>
        @if (node.task; as task) {
        <input
          type="checkbox"
          disabled
          [checked]="task.checked"
          [attr.aria-label]="task.checked ? 'Completed task' : 'Incomplete task'"
        />
        }
        <ng-container
          [markdownOutlet]="nodesView"
          [markdownContext]="{ $implicit: node.children, root, anchor, header }"
        />
      </li>
      } @case ('code-block') {
      <pre><code>{{ node.text }}</code></pre>
      } @case ('thematic-break') {
      <hr />
      } @case ('text') {<ng-container>{{ node.text }}</ng-container
      >} @case ('emphasis') {
      <em
        ><ng-container
          [markdownOutlet]="nodesView"
          [markdownContext]="{
            $implicit: node.children,
            root,
            anchor,
            header
          }"
      /></em>
      } @case ('strong') {
      <strong
        ><ng-container
          [markdownOutlet]="nodesView"
          [markdownContext]="{
            $implicit: node.children,
            root,
            anchor,
            header
          }"
      /></strong>
      } @case ('strikethrough') {
      <del
        ><ng-container
          [markdownOutlet]="nodesView"
          [markdownContext]="{
            $implicit: node.children,
            root,
            anchor,
            header
          }"
      /></del>
      } @case ('inline-code') { <code class="inline-code">{{ node.text }}</code> } @case ('link') {
      @if (!anchor && url(node.url, 'link'); as destination) {
      <a [href]="destination" [title]="node.title"
        ><ng-container
          [markdownOutlet]="nodesView"
          [markdownContext]="{
            $implicit: node.children,
            root,
            anchor: true,
            header
          }"
      /></a>
      } @else {
      <ng-container
        [markdownOutlet]="nodesView"
        [markdownContext]="{ $implicit: node.children, root, anchor, header }"
      />
      } } @case ('autolink') { @if (!anchor && url(node.url, 'link'); as
      destination) { <a [href]="destination">{{ node.text }}</a> } @else
      {<ng-container>{{ node.text }}</ng-container
      >} } @case ('link-reference') { @if (node.resolved) { @if (!anchor &&
      url(node.url, 'link'); as destination) {
      <a [href]="destination" [title]="node.title"
        ><ng-container
          [markdownOutlet]="nodesView"
          [markdownContext]="{
            $implicit: node.children,
            root,
            anchor: true,
            header
          }"
      /></a>
      } @else {
      <ng-container
        [markdownOutlet]="nodesView"
        [markdownContext]="{ $implicit: node.children, root, anchor, header }"
      />
      } } @else {<ng-container>[</ng-container
      ><ng-container
        [markdownOutlet]="nodesView"
        [markdownContext]="{ $implicit: node.children, root, anchor, header }"
      /><ng-container>{{ ']' + referenceSuffix(node) }}</ng-container
      >} } @case ('image') { @for (image of [node]; track image.url)
      { <threadplane-markdown-image [image]="image" /> } } @case ('soft-break')
      {<ng-container>{{ '\\n' }}</ng-container
      >} @case ('hard-break') { <br />
      } @case ('table') {
      <table>
        <thead>
          <ng-container
            [markdownOutlet]="nodesView"
            [markdownContext]="{
              $implicit: tableRows(node, true),
              root,
              anchor,
              header: true
            }"
          />
        </thead>
        <tbody>
          <ng-container
            [markdownOutlet]="nodesView"
            [markdownContext]="{
              $implicit: tableRows(node, false),
              root,
              anchor,
              header: false
            }"
          />
        </tbody>
      </table>
      } @case ('table-row') {
      <tr>
        <ng-container
          [markdownOutlet]="nodesView"
          [markdownContext]="{
            $implicit: node.children,
            root,
            anchor,
            header: node.isHeader
          }"
        />
      </tr>
      } @case ('table-cell') { @if (header) {
      <th [style.text-align]="node.alignment">
        <ng-container
          [markdownOutlet]="nodesView"
          [markdownContext]="{ $implicit: node.children, root, anchor, header }"
        />
      </th>
      } @else {
      <td [style.text-align]="node.alignment">
        <ng-container
          [markdownOutlet]="nodesView"
          [markdownContext]="{ $implicit: node.children, root, anchor, header }"
        />
      </td>
      } } @case ('citation-reference') { @if (root.citations.get(node.refId); as
      citation) {
      <sup [attr.aria-label]="'Citation ' + citation.index">{{
        '[' + citation.index + ']'
      }}</sup>
      } @else {
      <sup [attr.aria-label]="'Unresolved citation ' + node.refId">{{
        '[^' + node.refId + ']'
      }}</sup>
      } } @case ('math-inline') {<ng-container>{{
        mathSource(node)
      }}</ng-container
      >} @case ('math-display') {
      <pre>{{ mathSource(node) }}</pre>
      } @case ('html-inline') {<ng-container>{{ node.raw }}</ng-container
      >} @case ('html-block') {
      <pre>{{ node.raw }}</pre>
      } } }
    </ng-template>
  `,
  styles: `
    :host {
      display: block;
      color: var(--ds-text-primary, #142435);
      font-family: inherit;
      white-space: pre-wrap;
      overflow-wrap: anywhere;
    }
    pre { white-space: pre-wrap; overflow-wrap: anywhere; }
    .inline-code { white-space: pre-wrap; }
  `,
})
export class MarkdownComponent {
  readonly snapshot = input.required<MarkdownSnapshot>();
  protected readonly url = markdownUrl;
  protected tableRows(
    node: Extract<MarkdownNode, { type: 'table' }>,
    header: boolean
  ): readonly MarkdownNode[] {
    return node.children.filter((row) => row.isHeader === header);
  }
  protected referenceSuffix(
    node: Extract<MarkdownNode, { type: 'link-reference' }>
  ): string {
    return node.form === 'full'
      ? '[' + node.label + ']'
      : node.form === 'collapsed'
      ? '[]'
      : '';
  }
  protected mathSource(
    node: Extract<MarkdownNode, { type: 'math-inline' | 'math-display' }>
  ) {
    if (node.type === 'math-inline')
      return node.delimiter === '$'
        ? '$' + node.text + '$'
        : '\\(' + node.text + '\\)';
    return node.delimiter === '$$'
      ? '$$\n' + node.text + '\n$$'
      : '\\[' + node.text + '\\]';
  }
}

// libs/react/src/markdown/markdown.tsx
'use client';
import { Fragment, createElement } from 'react';
import {
  markdownUrl,
  type CitationDefinition,
  type MarkdownNode,
  type MarkdownSnapshot,
} from '@threadplane/content/markdown';
import { MarkdownImage } from './markdown-image.js';

export interface MarkdownProps {
  readonly snapshot: MarkdownSnapshot;
}
/** Present an accepted snapshot. Its lifetime belongs to the application. */
export function Markdown({ snapshot }: MarkdownProps) {
  return (
    <div
      style={{
        color: 'var(--ds-text-primary, #142435)',
        fontFamily: 'inherit',
        whiteSpace: 'pre-wrap',
        overflowWrap: 'anywhere',
      }}
    >
      {snapshot.root && (
        <NodeView
          key={snapshot.document.generation}
          node={snapshot.root}
          citations={snapshot.root.citations}
        />
      )}
    </div>
  );
}

function NodeView({
  node,
  citations,
  header = false,
  insideAnchor = false,
}: {
  readonly node: MarkdownNode;
  readonly citations: ReadonlyMap<string, CitationDefinition>;
  readonly header?: boolean;
  readonly insideAnchor?: boolean;
}) {
  const href =
    !insideAnchor &&
    (node.type === 'link' ||
      node.type === 'autolink' ||
      (node.type === 'link-reference' && node.resolved))
      ? markdownUrl(node.url, 'link')
      : undefined;
  const children =
    'children' in node
      ? node.children.map((child) => (
          <NodeView
            key={`${child.type}:${child.id}`}
            node={child}
            citations={citations}
            header={node.type === 'table-row' && node.isHeader}
            insideAnchor={insideAnchor || href !== undefined}
          />
        ))
      : null;
  switch (node.type) {
    case 'document':
      return <Fragment>{children}</Fragment>;
    case 'paragraph':
      return <p>{children}</p>;
    case 'heading':
      return createElement(`h${node.level}`, null, children);
    case 'blockquote':
      return <blockquote>{children}</blockquote>;
    case 'list':
      return node.ordered ? (
        <ol start={node.start ?? undefined}>{children}</ol>
      ) : (
        <ul>{children}</ul>
      );
    case 'list-item':
      return (
        <li>
          {node.task && (
            <input
              type="checkbox"
              checked={node.task.checked}
              disabled
              aria-label={
                node.task.checked ? 'Completed task' : 'Incomplete task'
              }
            />
          )}
          {children}
        </li>
      );
    case 'code-block':
      return (
        <pre style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>
          <code>{node.text}</code>
        </pre>
      );
    case 'thematic-break':
      return <hr />;
    case 'text':
      return node.text;
    case 'emphasis':
      return <em>{children}</em>;
    case 'strong':
      return <strong>{children}</strong>;
    case 'strikethrough':
      return <del>{children}</del>;
    case 'inline-code':
      return <code>{node.text}</code>;
    case 'link': {
      return href ? (
        <a href={href} title={node.title || undefined}>
          {children}
        </a>
      ) : (
        <Fragment>{children}</Fragment>
      );
    }
    case 'autolink': {
      return href ? <a href={href}>{node.text}</a> : node.text;
    }
    case 'image': {
      const src = markdownUrl(node.url, 'image');
      return (
        <MarkdownImage key={src} src={src} alt={node.alt} title={node.title} />
      );
    }
    case 'soft-break':
      return '\n';
    case 'hard-break':
      return <br />;
    case 'table':
      return (
        <table>
          <thead>
            {node.children
              .filter((row) => row.isHeader)
              .map((row) => (
                <NodeView
                  key={`${row.type}:${row.id}`}
                  node={row}
                  citations={citations}
                  insideAnchor={insideAnchor}
                />
              ))}
          </thead>
          <tbody>
            {node.children
              .filter((row) => !row.isHeader)
              .map((row) => (
                <NodeView
                  key={`${row.type}:${row.id}`}
                  node={row}
                  citations={citations}
                  insideAnchor={insideAnchor}
                />
              ))}
          </tbody>
        </table>
      );
    case 'table-row':
      return <tr>{children}</tr>;
    case 'table-cell':
      return header ? (
        <th style={{ textAlign: node.alignment ?? undefined }}>{children}</th>
      ) : (
        <td style={{ textAlign: node.alignment ?? undefined }}>{children}</td>
      );
    case 'citation-reference': {
      // Parser 0.5.8 can overwrite the node's index with its sibling position.
      const definition = citations.get(node.refId);
      return definition ? (
        <sup aria-label={`Citation ${definition.index}`}>
          [{definition.index}]
        </sup>
      ) : (
        <sup aria-label={`Unresolved citation ${node.refId}`}>
          [^{node.refId}]
        </sup>
      );
    }
    case 'link-reference': {
      if (node.resolved)
        return href ? (
          <a href={href} title={node.title || undefined}>
            {children}
          </a>
        ) : (
          <Fragment>{children}</Fragment>
        );
      return (
        <Fragment>
          [{children}]
          {node.form === 'full'
            ? `[${node.label}]`
            : node.form === 'collapsed'
            ? '[]'
            : ''}
        </Fragment>
      );
    }
    case 'math-inline':
      return (
        <span>
          {node.delimiter === '$' ? `$${node.text}$` : `\\(${node.text}\\)`}
        </span>
      );
    case 'math-display':
      return (
        <pre style={{ whiteSpace: 'pre-wrap' }}>
          {node.delimiter === '$$'
            ? `$$\n${node.text}\n$$`
            : `\\[${node.text}\\]`}
        </pre>
      );
    case 'html-inline':
      return node.raw;
    case 'html-block':
      return <pre style={{ whiteSpace: 'pre-wrap' }}>{node.raw}</pre>;
    default: {
      const exhaustive: never = node;
      return exhaustive;
    }
  }
}
