// libs/angular/markdown/src/markdown.type-test.ts
import type { InputSignal } from '@angular/core';
import type { MarkdownSnapshot } from '@threadplane/content/markdown';
import { MarkdownComponent } from './public-api';

type Input = MarkdownComponent['snapshot'] extends InputSignal<infer T>
  ? T
  : never;
export function markdownContracts(snapshot: MarkdownSnapshot) {
  const accepted: Input = snapshot;
  // @ts-expect-error Raw strings are not accepted snapshots.
  const raw: Input = 'text';
  // @ts-expect-error Generation and phase are required together with root.
  const partial: Input = { root: null };
  // @ts-expect-error The accepted document is readonly.
  accepted.document.content = 'changed';
  if (accepted.root) {
    // @ts-expect-error Nested children remain readonly.
    accepted.root.children.push(accepted.root.children[0]);
    // @ts-expect-error Definitions are readonly maps.
    accepted.root.linkDefinitions.clear();
    const definition = accepted.root.citations.get('source');
    if (definition) {
      // @ts-expect-error Definition values are deeply readonly.
      definition.children[0].status = 'complete';
    }
  }
  return [accepted, raw, partial];
}

// libs/react/src/markdown/markdown.type-test.tsx
import {
  createMarkdown,
  type MarkdownSnapshot,
} from '@threadplane/content/markdown';
import { Markdown, type MarkdownProps } from './index.js';
const snapshot = createMarkdown({
  generation: 'a',
  phase: 'complete',
  content: '',
}).getSnapshot();
const props: MarkdownProps = { snapshot };
<Markdown {...props} />;
// @ts-expect-error Whole accepted snapshot is required.
<Markdown />;
// @ts-expect-error String parsing is not a view responsibility.
<Markdown snapshot="text" />;
// @ts-expect-error No owner convenience prop.
<Markdown snapshot={snapshot} owner={{}} />;
// @ts-expect-error Props are readonly.
props.snapshot = snapshot;
export function readonlyInput(value: MarkdownSnapshot) {
  // @ts-expect-error Nested document is readonly.
  value.document.content = 'changed';
  if (value.root) {
    // @ts-expect-error Owned nodes cannot be changed by a view.
    value.root.children.pop();
  }
}
